mode: development
media_root: media
media_url: /media
base_url: /
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.SorterPlugin
    - hyde.ext.plugins.meta.TaggerPlugin
    - hyde.ext.plugins.text.SyntextPlugin
    - hyde.ext.plugins.text.TextlinksPlugin

context:
    data:
        site:
            name: Roman Bogorodskiy

markdown:
    extensions:
        - markdown.extensions.toc
